### ISSUE TITLE
Kotlin data class properties do not give default values ​​error

### ISSUE THREAD

**Issue by dora4** [dora4/dcache-android#14]
Caused by: java.lang.NullPointerException: null receiver
                                                                                                    	at java.lang.reflect.Field.set(Native Method)
                                                                                                    	at dora.db.dao.OrmDao.createResult(OrmDao.kt:630)
                                                                                                    	at dora.db.dao.OrmDao.getResult(OrmDao.kt:531)
                                                                                                    	at dora.db.dao.OrmDao.selectInternal(OrmDao.kt:402)
                                                                                                    	at dora.db.dao.OrmDao.select(OrmDao.kt:388)
                                                                                                    	at dora.db.dao.OrmDao.select(OrmDao.kt:384)
                                                                                                    	at com.doracrypto.crypto.ui.activity.AccountActivity.fetchAccounts(AccountActivity.kt:66)
                                                                                                    	at com.doracrypto.crypto.ui.activity.AccountActivity.initData(AccountActivity.kt:60)
                                                                                                    	at com.doracrypto.crypto.ui.activity.AccountActivity.initData(AccountActivity.kt:23)
                                                                                                    	at dora.BaseActivity.onCreate(BaseActivity.java:147)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by dora4** [comment]
Occurs in the implementation class of OrmTable
